[package]
name = "fetch-one"
authors = ["itowlson <ivan.towlson@fermyon.com>"]
description = ""
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
<<<<<<< HEAD
spin-sdk = { git = "https://github.com/fermyon/spin-rust-sdk", branch = "main" }
=======
spin-sdk = "3.0"
>>>>>>> origin
spin-sqlx = { path = "../.." }
sqlx = "0.8.0"

[workspace]
